name: Deploy Issue Tracker

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd /var/www/applioIssueTracker/applioIssueTracker

            echo "Fetching latest code..."
            git fetch origin

            echo "Resetting production..."
            git reset --hard origin/production

            echo "Cleaning files..."
            git clean -fd

            echo "Building containers..."
            docker compose up -d --build

            echo "Deployment completed"